cls: ctrl_sac
discount: 0.99
tau: 0.005
alpha: 0.2
auto_entropy: true

target_update_freq: 2 # tune

critic_hidden_dims: [256, 256] # this is actually not used. this is only for compatibility
actor_hidden_dims: [256, 256]

critic_lr: 0.0003
actor_lr: 0.0003
alpha_lr: 0.0003

# below are params specific to ctrl_sac
feature_dim: 2048
feature_lr: 0.0003 # tune
phi_hidden_dims: [1024, 1024]
mu_hidden_dims: [1024, 1024]
reward_coef: 0.5
feature_update_ratio: 4 # tune
temperature: 1.0
critic_hidden_dim: 256
